streamKM = read.csv("streamKM.csv", sep=";")
streamKM <- data.frame(streamKM[,-1], row.names = streamKM[,1])
withKMeans = read.csv("withKmeans.csv", sep=";")
withKMeans <- data.frame(withKMeans[,-1], row.names = withKMeans[,1])
BICO = read.csv("BICO.csv", sep=";")
BICO <- data.frame(BICO[,-1], row.names = BICO[,1])
plot(streamKM[,3], type = "b", pch = 20, col = "blue", main="Silhouette Comparison", ylim=c(0.45,0.7), ylab="Average global silhouette",xlab="frequency = 1000 observations")
lines(withKMeans[,3], type = "b", pch = 20, col = "green3")
lines(BICO[,3], type = "b", pch = 20, col = "red")
legend("bottomleft",legend = c("streamKM", "withKMeans", "BICO"), col = c("blue","green3", "red"),lwd=2)
plot(streamKM[,1], type = "b", pch = 20, col = "blue", main="SSQ Comparison", ylab="SSQ", ylim=c(1700,2300),xlab="frequency = 1000 observations")
lines(withKMeans[,1], type = "b", pch = 20, col = "green3")
lines(BICO[,1], type = "b", pch = 20, col = "red")
legend("bottomright",legend = c("streamKM", "withKMeans", "BICO"), col = c("blue","green3", "red"),lwd=2)
